### ISSUE TITLE
Pragma support

### ISSUE THREAD

**Issue by tmcw** [observablehq/htl#2]
An eventuality if we want the same syntax to support React/Preact/Choo/etc outputs would be support for a [pragma](https://babeljs.io/docs/en/babel-plugin-transform-react-jsx#pragma) like React.createElement.

**Comment by mbostock** [comment]
Folding this discussion into #3. I’m pretty sure this isn’t possible in the context of hypertext literal because it concatenates markup rather than materializing an intermediate DOM representation.
