### ISSUE TITLE
html`<html>` is null

### ISSUE THREAD

**Issue by tomlarkworthy** [observablehq/htl#20]
Also html`<head>` is null
Also html`<body>` is null

(I was trying to make a full webpage with this).

**Comment by clarkevans** [comment]
Also be on the lookout for issues related to [foster parenting](https://html.spec.whatwg.org/multipage/parsing.html#foster-parent).

**Comment by mbostock** [comment]
I think this probably should be the expected behavior given that it is compatible with how template elements behave:

```js
const template = document.createElement("template");
template.innerHTML = "<body>";
template.content.firstChild; // null
```
